import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useUser } from '@auth0/nextjs-auth0/client';
import Link from 'next/link';


const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  const { user, error, isLoading } = useUser();
  async function handleClick() {
    const email = 'boris4@email.com'
    const request = await fetch('http://localhost:3000/api/auth/hook', {   // "localhost:3000" will be replaced before deploying this Action
      method: 'POST',
      body: JSON.stringify({ email, secret: process.env.AUTH0_HOOK_SECRET }),
      headers: { 'Content-Type': 'application/json' },
    })
    console.log(request)
  }

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='flex flex-col items-center h-screen items-center'>
          <Link

            className='text-lg py-3 px-6 border'
            href="/api/auth/login"
          >
            Login
          </Link>
          <Link
            className='text-lg py-3 px-6 border'
            href="/api/auth/logout"
          >
            logout
          </Link>
          <Link
            className='text-lg py-3 px-6 border'
            href="/dashboard"
          >
            Go to Dashboard
          </Link>
        </div>
      </main>
    </>
  )
}
